[package]
name = "mcr"
version = "0.1.0"
edition = "2021"
license.workspace = true
authors.workspace = true
description = "Rusty Midnight Commander - mcr binary"
repository = "https://github.com/vburenin/rusty-midnight-commander"
autobins = false

[dependencies]
anyhow.workspace = true
rmc-core = { path = "../rmc-core" }
rmc-fs = { path = "../rmc-fs" }
rmc-ui = { path = "../rmc-ui" }

[features]
default = []

[[bin]]
name = "mcr"
path = "src/main.rs"
