[package]
name = "rmc-fs"
version = "0.1.0"
edition = "2021"
license.workspace = true
authors.workspace = true
description = "VFS trait and local filesystem implementation for RMC"

[dependencies]
anyhow.workspace = true
thiserror.workspace = true
walkdir.workspace = true
time.workspace = true
unicode-width.workspace = true
serde.workspace = true
users.workspace = true
tar = "0.4"
flate2 = { version = "1.0", features = ["rust_backend"] }
zip = { version = "0.6", default-features = false, features = ["deflate"] }

[dev-dependencies]
tempfile = "3.10"
